package com.swingtech.app.tabletracker.model;

public enum EventFailureReasonEnum {
	SYSTEM_ERROR,
	CURRENT_EVENT_EXISTS_FOR_START_LOGGING,
	NO_CURRENT_EVENT_FOR_END_LOGGING,
	INVALID_START_EVENT_REQUEST,
	INVALID_END_EVENT_REQUEST,
	INVALID_CURRENT_EVENT_FOR_END_EVENT_REQUEST
}
